import { Router } from "express";
import userRoutes from "./user.routes";
import categoryRoutes from "./category.routes";
import typeRoutes from "./type.routes";
import tagRoutes from "./tag.routes";
import serviceRoutes from "./service.routes";
import templeRoutes from "./temple.routes";
import bannerRoutes from "./banner.routes";
import popularRoutes from "./popular.routes";
import testimonialRoutes from "./testimonial.routes";
import servicePlacementRoutes from "./service-placement.routes";
import blogRoutes from "./blog.routes";
import blogCategoryRoutes from "./blog-category.routes";
import blogAuthorRoutes from "./blog-author.routes";
import aayojanRoutes from "./aayojan.routes";
import couponRoutes from "./coupon.routes";
import reviewRoutes from "./review.routes";
import invoiceRoutes from "./invoice.routes";
import panditAssignmentRoutes from "./pandit.routes";
import panditProfileRoutes from "./pandit-profile.routes";
import contactRoutes from "./contact.routes";
import dashboardRoutes from "./dashboard.routes";
import orderRoutes from "./order.routes";
import notificationRoutes from "./notification.routes";
import settingsRoutes from "./settings.routes";
import addonRoutes from "./addon.routes";
import galleryRoutes from "./gallery.routes";
import exportRoutes from "./export.routes";
import pujaProcessRoutes from "./puja-process.routes";

const router = Router();

router.use("/users", userRoutes);
router.use("/categories", categoryRoutes);
router.use("/types", typeRoutes);
router.use("/tags", tagRoutes);
router.use("/services", serviceRoutes);
router.use("/temples", templeRoutes);
router.use("/banners", bannerRoutes);
router.use("/popular-searches", popularRoutes);
router.use("/testimonials", testimonialRoutes);
router.use("/service-placements", servicePlacementRoutes);
router.use("/blogs", blogRoutes);
router.use("/blog-categories", blogCategoryRoutes);
router.use("/blog-authors", blogAuthorRoutes);
router.use("/aayojan", aayojanRoutes);
router.use("/coupons", couponRoutes);
router.use("/reviews", reviewRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/pandit-assignments", panditAssignmentRoutes);
router.use("/pandits", panditProfileRoutes);
router.use("/contact-entries", contactRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/orders", orderRoutes);
router.use("/notifications", notificationRoutes);
router.use("/app-settings", settingsRoutes);
router.use("/addons", addonRoutes);
router.use("/gallery", galleryRoutes);
router.use("/export", exportRoutes);
router.use("/puja-processes", pujaProcessRoutes);

export default router;
